// Български пазар на труда - Данни за AI експозиция
// Базирано на данни от НСИ (Национален статистически институт) и класификация ISCO-08
// Данни за заетост по предварителни данни на НСИ за 2024 (~3.4М общо заети)
//
// МЕТОДОЛОГИЯ НА ОЦЕНКИТЕ:
// AI експозицията (0-10) е базирана на три ключови изследвания:
// 1. OpenAI "GPTs are GPTs" (Eloundou et al., 2023) - задачово-базиран анализ на 1000+ професии
// 2. ILO "Generative AI and Jobs" (2024) - глобален индекс по ISCO-08 класификация
// 3. Bruegel "Exposure to GenAI in the European Labour Market" (2024) - EU-специфичен анализ
//
// Скала: 0 = няма експозиция (физическа, нецифрова работа)
//        5 = умерена (смесени задачи, частично цифрови)
//       10 = пълна експозиция (изцяло цифров/текстов продукт)
//
// Принцип (Karpathy, 2026): "Ако работният продукт е изцяло цифров и ролята
// може да се изпълнява от вкъщи, експозицията е по подразбиране висока."

const occupations = [
  // --- РЪКОВОДИТЕЛИ ---
  { name: "Висши ръководители и законодатели", employment: 18500, ai_score: 5, category: "Ръководители", avg_salary_eur: 3170 },
  { name: "Административни и търговски ръководители", employment: 32000, ai_score: 6, category: "Ръководители", avg_salary_eur: 2454 },
  { name: "Ръководители в производството", employment: 28000, ai_score: 5, category: "Ръководители", avg_salary_eur: 2301 },
  { name: "Ръководители в хотелиерството и търговията", employment: 35000, ai_score: 5, category: "Ръководители", avg_salary_eur: 1636 },
  { name: "ИКТ ръководители", employment: 12000, ai_score: 6, category: "Ръководители", avg_salary_eur: 3835 },
  { name: "Ръководители в строителството", employment: 15000, ai_score: 3, category: "Ръководители", avg_salary_eur: 2147 },
  { name: "Ръководители доставки и дистрибуция", employment: 11000, ai_score: 5, category: "Ръководители", avg_salary_eur: 1943 },

  // --- СПЕЦИАЛИСТИ ---
  { name: "Софтуерни разработчици и програмисти", employment: 62000, ai_score: 8, category: "Специалисти", avg_salary_eur: 3477 },
  { name: "Специалисти по бази данни и мрежи", employment: 18000, ai_score: 7, category: "Специалисти", avg_salary_eur: 2812 },
  { name: "Лекари", employment: 32000, ai_score: 4, category: "Специалисти", avg_salary_eur: 2147 },
  { name: "Медицински сестри и акушерки", employment: 34000, ai_score: 3, category: "Специалисти", avg_salary_eur: 1432 },
  { name: "Преподаватели във висши училища", employment: 22000, ai_score: 5, category: "Специалисти", avg_salary_eur: 1841 },
  { name: "Начални учители", employment: 28000, ai_score: 4, category: "Специалисти", avg_salary_eur: 1329 },
  { name: "Предучилищни педагози", employment: 20000, ai_score: 3, category: "Специалисти", avg_salary_eur: 1227 },
  { name: "Учители в средни училища", employment: 38000, ai_score: 4, category: "Специалисти", avg_salary_eur: 1380 },
  { name: "Счетоводители", employment: 42000, ai_score: 9, category: "Специалисти", avg_salary_eur: 1636 },
  { name: "Финансови анализатори и консултанти", employment: 15000, ai_score: 9, category: "Специалисти", avg_salary_eur: 2454 },
  { name: "Адвокати", employment: 16000, ai_score: 7, category: "Специалисти", avg_salary_eur: 2301 },
  { name: "Архитекти и инженери", employment: 35000, ai_score: 5, category: "Специалисти", avg_salary_eur: 1943 },
  { name: "Електроинженери", employment: 14000, ai_score: 5, category: "Специалисти", avg_salary_eur: 1841 },
  { name: "Строителни инженери", employment: 12000, ai_score: 4, category: "Специалисти", avg_salary_eur: 1790 },
  { name: "Фармацевти", employment: 8500, ai_score: 5, category: "Специалисти", avg_salary_eur: 1738 },
  { name: "Зъболекари", employment: 7200, ai_score: 3, category: "Специалисти", avg_salary_eur: 2045 },
  { name: "Ветеринарни лекари", employment: 4500, ai_score: 3, category: "Специалисти", avg_salary_eur: 1432 },
  { name: "Социални работници", employment: 12000, ai_score: 4, category: "Специалисти", avg_salary_eur: 1278 },
  { name: "Психолози", employment: 5500, ai_score: 5, category: "Специалисти", avg_salary_eur: 1432 },
  { name: "Специалисти човешки ресурси", employment: 18000, ai_score: 7, category: "Специалисти", avg_salary_eur: 1738 },
  { name: "Маркетинг и PR специалисти", employment: 22000, ai_score: 8, category: "Специалисти", avg_salary_eur: 1841 },
  { name: "Журналисти и редактори", employment: 8000, ai_score: 8, category: "Специалисти", avg_salary_eur: 1329 },
  { name: "Преводачи и тълковници", employment: 6500, ai_score: 9, category: "Специалисти", avg_salary_eur: 1432 },
  { name: "Артисти и изпълнители", employment: 9000, ai_score: 5, category: "Специалисти", avg_salary_eur: 1125 },
  { name: "Икономисти", employment: 14000, ai_score: 8, category: "Специалисти", avg_salary_eur: 1636 },
  { name: "Еколози", employment: 4000, ai_score: 4, category: "Специалисти", avg_salary_eur: 1432 },
  { name: "Биолози", employment: 3500, ai_score: 4, category: "Специалисти", avg_salary_eur: 1329 },
  { name: "Математици и статистици", employment: 2500, ai_score: 7, category: "Специалисти", avg_salary_eur: 1943 },
  { name: "Графични и мултимедийни дизайнери", employment: 12000, ai_score: 8, category: "Специалисти", avg_salary_eur: 1636 },
  { name: "Уеб разработчици", employment: 15000, ai_score: 8, category: "Специалисти", avg_salary_eur: 2659 },
  { name: "Системни анализатори", employment: 8000, ai_score: 8, category: "Специалисти", avg_salary_eur: 2965 },
  { name: "QA и тест инженери", employment: 11000, ai_score: 7, category: "Специалисти", avg_salary_eur: 2454 },
  { name: "Анализатори на данни", employment: 6000, ai_score: 8, category: "Специалисти", avg_salary_eur: 2812 },
  { name: "Научни изследователи", employment: 8000, ai_score: 5, category: "Специалисти", avg_salary_eur: 1534 },

  // --- ТЕХНИЦИ И ПРИЛОЖНИ СПЕЦИАЛИСТИ ---
  { name: "ИКТ техници и поддръжка", employment: 22000, ai_score: 6, category: "Техници", avg_salary_eur: 1738 },
  { name: "Инженерни техници", employment: 28000, ai_score: 5, category: "Техници", avg_salary_eur: 1432 },
  { name: "Медицински и фармацевтични техници", employment: 18000, ai_score: 4, category: "Техници", avg_salary_eur: 1227 },
  { name: "Зъботехници", employment: 4500, ai_score: 3, category: "Техници", avg_salary_eur: 1329 },
  { name: "Помощник-медицински сестри", employment: 25000, ai_score: 3, category: "Техници", avg_salary_eur: 1125 },
  { name: "Брокери на недвижими имоти", employment: 8000, ai_score: 7, category: "Техници", avg_salary_eur: 1534 },
  { name: "Застрахователни агенти и брокери", employment: 12000, ai_score: 7, category: "Техници", avg_salary_eur: 1432 },
  { name: "Търговски представители", employment: 45000, ai_score: 5, category: "Техници", avg_salary_eur: 1329 },
  { name: "Митнически и гранични инспектори", employment: 6000, ai_score: 5, category: "Техници", avg_salary_eur: 1432 },
  { name: "Данъчни и акцизни служители", employment: 8000, ai_score: 6, category: "Техници", avg_salary_eur: 1329 },
  { name: "Полицейски служители", employment: 32000, ai_score: 2, category: "Техници", avg_salary_eur: 1432 },
  { name: "Социални асистенти", employment: 14000, ai_score: 4, category: "Техници", avg_salary_eur: 920 },
  { name: "Спортни треньори и инструктори", employment: 7000, ai_score: 2, category: "Техници", avg_salary_eur: 1023 },
  { name: "Фотографи", employment: 3500, ai_score: 6, category: "Техници", avg_salary_eur: 1125 },
  { name: "Техници в медиите", employment: 3000, ai_score: 6, category: "Техници", avg_salary_eur: 1329 },
  { name: "Счетоводни специалисти", employment: 35000, ai_score: 8, category: "Техници", avg_salary_eur: 1227 },
  { name: "Административни секретари", employment: 15000, ai_score: 8, category: "Техници", avg_salary_eur: 1125 },
  { name: "Юридически сътрудници", employment: 8000, ai_score: 6, category: "Техници", avg_salary_eur: 1329 },
  { name: "Лабораторни техници", employment: 6000, ai_score: 4, category: "Техници", avg_salary_eur: 1125 },
  { name: "Инспектори по качество и безопасност", employment: 9000, ai_score: 4, category: "Техници", avg_salary_eur: 1227 },
  { name: "Транспортни диспечери", employment: 7000, ai_score: 5, category: "Техници", avg_salary_eur: 1227 },

  // --- ПОМОЩЕН АДМИНИСТРАТИВЕН ПЕРСОНАЛ ---
  { name: "Общи офис служители", employment: 48000, ai_score: 8, category: "Административни", avg_salary_eur: 1023 },
  { name: "Секретари", employment: 22000, ai_score: 8, category: "Административни", avg_salary_eur: 920 },
  { name: "Оператори за въвеждане на данни", employment: 12000, ai_score: 9, category: "Административни", avg_salary_eur: 920 },
  { name: "Служители ТРЗ", employment: 14000, ai_score: 8, category: "Административни", avg_salary_eur: 1125 },
  { name: "Банкови касиери", employment: 15000, ai_score: 8, category: "Административни", avg_salary_eur: 1227 },
  { name: "Счетоводни служители", employment: 32000, ai_score: 9, category: "Административни", avg_salary_eur: 1023 },
  { name: "Складови и транспортни служители", employment: 18000, ai_score: 6, category: "Административни", avg_salary_eur: 920 },
  { name: "Рецепционисти", employment: 16000, ai_score: 7, category: "Административни", avg_salary_eur: 818 },
  { name: "Телефонни оператори", employment: 5000, ai_score: 9, category: "Административни", avg_salary_eur: 716 },
  { name: "Пощенски служители и куриери", employment: 8000, ai_score: 6, category: "Административни", avg_salary_eur: 818 },
  { name: "Библиотечни служители", employment: 4500, ai_score: 7, category: "Административни", avg_salary_eur: 716 },
  { name: "Служители човешки ресурси", employment: 9000, ai_score: 7, category: "Административни", avg_salary_eur: 1023 },
  { name: "Информационни служители", employment: 14000, ai_score: 7, category: "Административни", avg_salary_eur: 920 },

  // --- УСЛУГИ И ТЪРГОВИЯ ---
  { name: "Екскурзоводи и пътнически служители", employment: 6000, ai_score: 4, category: "Услуги и търговия", avg_salary_eur: 1023 },
  { name: "Таксиметрови шофьори", employment: 15000, ai_score: 4, category: "Услуги и търговия", avg_salary_eur: 1023 },
  { name: "Готвачи", employment: 38000, ai_score: 3, category: "Услуги и търговия", avg_salary_eur: 818 },
  { name: "Сервитьори и бармани", employment: 45000, ai_score: 3, category: "Услуги и търговия", avg_salary_eur: 767 },
  { name: "Фризьори и козметици", employment: 18000, ai_score: 2, category: "Услуги и търговия", avg_salary_eur: 818 },
  { name: "Продавач-консултанти", employment: 145000, ai_score: 3, category: "Услуги и търговия", avg_salary_eur: 716 },
  { name: "Касиери", employment: 42000, ai_score: 6, category: "Услуги и търговия", avg_salary_eur: 716 },
  { name: "Пазарни и улични продавачи", employment: 15000, ai_score: 3, category: "Услуги и търговия", avg_salary_eur: 614 },
  { name: "Детегледачки", employment: 15000, ai_score: 2, category: "Услуги и търговия", avg_salary_eur: 716 },
  { name: "Лични помощници в здравеопазването", employment: 22000, ai_score: 2, category: "Услуги и търговия", avg_salary_eur: 818 },
  { name: "Охранители", employment: 32000, ai_score: 3, category: "Услуги и търговия", avg_salary_eur: 716 },
  { name: "Пожарникари", employment: 8500, ai_score: 1, category: "Услуги и търговия", avg_salary_eur: 1125 },
  { name: "Служители в кол центрове", employment: 28000, ai_score: 9, category: "Услуги и търговия", avg_salary_eur: 920 },
  { name: "Хотелски рецепционисти", employment: 12000, ai_score: 6, category: "Услуги и търговия", avg_salary_eur: 818 },
  { name: "Погребални работници", employment: 3000, ai_score: 1, category: "Услуги и търговия", avg_salary_eur: 920 },
  { name: "Грижа за животни", employment: 4000, ai_score: 1, category: "Услуги и търговия", avg_salary_eur: 716 },
  { name: "Домоуправители", employment: 18000, ai_score: 1, category: "Услуги и търговия", avg_salary_eur: 614 },
  { name: "Ръководители хигиена и чистота", employment: 8000, ai_score: 3, category: "Услуги и търговия", avg_salary_eur: 716 },

  // --- ЗЕМЕДЕЛИЕ, ГОРСКО И РИБНО СТОПАНСТВО ---
  { name: "Полевъдци и зеленчукопроизводители", employment: 55000, ai_score: 2, category: "Земеделие", avg_salary_eur: 716 },
  { name: "Овощари и лозари", employment: 22000, ai_score: 2, category: "Земеделие", avg_salary_eur: 716 },
  { name: "Животновъди и млекопроизводители", employment: 28000, ai_score: 2, category: "Земеделие", avg_salary_eur: 614 },
  { name: "Смесени земеделски стопани", employment: 35000, ai_score: 2, category: "Земеделие", avg_salary_eur: 614 },
  { name: "Горски работници", employment: 12000, ai_score: 1, category: "Земеделие", avg_salary_eur: 716 },
  { name: "Рибари и аквакултури", employment: 4000, ai_score: 2, category: "Земеделие", avg_salary_eur: 716 },
  { name: "Градинари и озеленители", employment: 15000, ai_score: 1, category: "Земеделие", avg_salary_eur: 614 },
  { name: "Дребни земеделски стопани", employment: 18000, ai_score: 1, category: "Земеделие", avg_salary_eur: 486 },

  // --- ЗАНАЯТЧИИ И СРОДНИ ---
  { name: "Строители - груб и довършителен строеж", employment: 65000, ai_score: 2, category: "Занаяти", avg_salary_eur: 1023 },
  { name: "Електротехници и електромонтьори", employment: 28000, ai_score: 3, category: "Занаяти", avg_salary_eur: 1125 },
  { name: "Водопроводчици и тръбопроводчици", employment: 18000, ai_score: 2, category: "Занаяти", avg_salary_eur: 1023 },
  { name: "Бояджии и строителни чистачи", employment: 15000, ai_score: 2, category: "Занаяти", avg_salary_eur: 920 },
  { name: "Металообработващи и заварчици", employment: 32000, ai_score: 3, category: "Занаяти", avg_salary_eur: 1023 },
  { name: "Ковачи и инструментчици", employment: 12000, ai_score: 3, category: "Занаяти", avg_salary_eur: 1125 },
  { name: "Механици и монтьори на машини", employment: 42000, ai_score: 3, category: "Занаяти", avg_salary_eur: 1125 },
  { name: "Автомонтьори", employment: 25000, ai_score: 3, category: "Занаяти", avg_salary_eur: 1023 },
  { name: "Електронни механици и сервизни техници", employment: 14000, ai_score: 4, category: "Занаяти", avg_salary_eur: 1227 },
  { name: "Шивачи и конфекционери", employment: 45000, ai_score: 3, category: "Занаяти", avg_salary_eur: 716 },
  { name: "Обущари и кожари", employment: 8000, ai_score: 3, category: "Занаяти", avg_salary_eur: 716 },
  { name: "Дърводелци и дървообработващи", employment: 18000, ai_score: 2, category: "Занаяти", avg_salary_eur: 920 },
  { name: "Мебелисти", employment: 12000, ai_score: 3, category: "Занаяти", avg_salary_eur: 818 },
  { name: "Хлебари и сладкари", employment: 14000, ai_score: 2, category: "Занаяти", avg_salary_eur: 716 },
  { name: "Месари и рибопреработватели", employment: 8000, ai_score: 2, category: "Занаяти", avg_salary_eur: 716 },
  { name: "Печатари", employment: 6000, ai_score: 5, category: "Занаяти", avg_salary_eur: 1023 },
  { name: "Стъклари и керамици", employment: 5000, ai_score: 2, category: "Занаяти", avg_salary_eur: 818 },
  { name: "Покривни майстори", employment: 8000, ai_score: 1, category: "Занаяти", avg_salary_eur: 1023 },

  // --- МАШИННИ ОПЕРАТОРИ И МОНТАЖНИЦИ ---
  { name: "Оператори в минната промишленост", employment: 18000, ai_score: 3, category: "Оператори", avg_salary_eur: 1329 },
  { name: "Оператори в металообработването", employment: 15000, ai_score: 3, category: "Оператори", avg_salary_eur: 1125 },
  { name: "Оператори в химическата промишленост", employment: 12000, ai_score: 4, category: "Оператори", avg_salary_eur: 1125 },
  { name: "Оператори на каучук и пластмаси", employment: 14000, ai_score: 3, category: "Оператори", avg_salary_eur: 920 },
  { name: "Оператори на текстилни машини", employment: 28000, ai_score: 3, category: "Оператори", avg_salary_eur: 716 },
  { name: "Оператори в хранителната промишленост", employment: 22000, ai_score: 3, category: "Оператори", avg_salary_eur: 818 },
  { name: "Оператори дървообработващи машини", employment: 8000, ai_score: 3, category: "Оператори", avg_salary_eur: 818 },
  { name: "Оператори на хартиени машини", employment: 5000, ai_score: 3, category: "Оператори", avg_salary_eur: 818 },
  { name: "Монтажници на електрическо оборудване", employment: 35000, ai_score: 4, category: "Оператори", avg_salary_eur: 920 },
  { name: "Монтажници на електроника", employment: 22000, ai_score: 4, category: "Оператори", avg_salary_eur: 920 },
  { name: "Монтажници на машини", employment: 18000, ai_score: 3, category: "Оператори", avg_salary_eur: 920 },
  { name: "Шофьори на леки автомобили", employment: 42000, ai_score: 4, category: "Оператори", avg_salary_eur: 1023 },
  { name: "Шофьори на тежкотоварни и автобуси", employment: 65000, ai_score: 4, category: "Оператори", avg_salary_eur: 1125 },
  { name: "Локомотивни машинисти", employment: 4500, ai_score: 4, category: "Оператори", avg_salary_eur: 1329 },
  { name: "Корабни екипажи", employment: 3000, ai_score: 3, category: "Оператори", avg_salary_eur: 1636 },
  { name: "Крановици", employment: 6000, ai_score: 3, category: "Оператори", avg_salary_eur: 1125 },
  { name: "Мотокаристи", employment: 12000, ai_score: 4, category: "Оператори", avg_salary_eur: 920 },
  { name: "Оператори земеделски и горски машини", employment: 15000, ai_score: 3, category: "Оператори", avg_salary_eur: 818 },
  { name: "Оператори на стационарни машини", employment: 10000, ai_score: 4, category: "Оператори", avg_salary_eur: 1023 },
  { name: "Оператори фармацевтични машини", employment: 8000, ai_score: 4, category: "Оператори", avg_salary_eur: 1023 },

  // --- НИСКОКВАЛИФИЦИРАНИ ПРОФЕСИИ ---
  { name: "Чистачи и помощници", employment: 75000, ai_score: 1, category: "Нискоквалифицирани", avg_salary_eur: 614 },
  { name: "Земеделски работници", employment: 42000, ai_score: 1, category: "Нискоквалифицирани", avg_salary_eur: 511 },
  { name: "Строителни работници", employment: 35000, ai_score: 1, category: "Нискоквалифицирани", avg_salary_eur: 716 },
  { name: "Производствени работници", employment: 28000, ai_score: 2, category: "Нискоквалифицирани", avg_salary_eur: 614 },
  { name: "Ръчни опаковчици", employment: 22000, ai_score: 3, category: "Нискоквалифицирани", avg_salary_eur: 614 },
  { name: "Транспортни работници", employment: 15000, ai_score: 2, category: "Нискоквалифицирани", avg_salary_eur: 716 },
  { name: "Сметосъбирачи", employment: 12000, ai_score: 1, category: "Нискоквалифицирани", avg_salary_eur: 716 },
  { name: "Улични продавачи", employment: 8000, ai_score: 2, category: "Нискоквалифицирани", avg_salary_eur: 511 },
  { name: "Домашни помощници", employment: 15000, ai_score: 1, category: "Нискоквалифицирани", avg_salary_eur: 511 },
  { name: "Кухненски помощници", employment: 18000, ai_score: 2, category: "Нискоквалифицирани", avg_salary_eur: 511 },
  { name: "Помощници приготвяне на храна", employment: 12000, ai_score: 2, category: "Нискоквалифицирани", avg_salary_eur: 614 },
  { name: "Куриери и доставчици", employment: 25000, ai_score: 3, category: "Нискоквалифицирани", avg_salary_eur: 818 },
  { name: "Отчетници и инкасатори", employment: 4000, ai_score: 6, category: "Нискоквалифицирани", avg_salary_eur: 716 },
  { name: "Миньори и кариерни работници", employment: 6000, ai_score: 1, category: "Нискоквалифицирани", avg_salary_eur: 818 },

  // --- ВЪОРЪЖЕНИ СИЛИ ---
  { name: "Военни офицери", employment: 12000, ai_score: 3, category: "Въоръжени сили", avg_salary_eur: 1636 },
  { name: "Военнослужещи", employment: 28000, ai_score: 2, category: "Въоръжени сили", avg_salary_eur: 1227 },

  // --- ДОПЪЛНИТЕЛНИ (за пълнота на данните) ---
  { name: "Държавни и общински служители", employment: 85000, ai_score: 6, category: "Административни", avg_salary_eur: 1227 },
  { name: "Помощник-фармацевти", employment: 6000, ai_score: 4, category: "Техници", avg_salary_eur: 1125 },
  { name: "Зъболекарски асистенти", employment: 4000, ai_score: 3, category: "Техници", avg_salary_eur: 920 },
  { name: "Рехабилитатори и кинезитерапевти", employment: 5000, ai_score: 3, category: "Специалисти", avg_salary_eur: 1329 },
  { name: "Оптици", employment: 2000, ai_score: 3, category: "Техници", avg_salary_eur: 1125 },
  { name: "Пилоти и авиоперсонал", employment: 2500, ai_score: 3, category: "Оператори", avg_salary_eur: 3068 },
  { name: "Кондуктори в градски транспорт", employment: 3000, ai_score: 5, category: "Услуги и търговия", avg_salary_eur: 818 },
  { name: "Портиери и пазачи", employment: 12000, ai_score: 1, category: "Услуги и търговия", avg_salary_eur: 614 },
  { name: "Диетолози и нутриционисти", employment: 2000, ai_score: 4, category: "Специалисти", avg_salary_eur: 1227 },
  { name: "Логопеди и ерготерапевти", employment: 3500, ai_score: 3, category: "Специалисти", avg_salary_eur: 1227 },
  { name: "Служители в енергетиката", employment: 25000, ai_score: 4, category: "Оператори", avg_salary_eur: 1432 },
  { name: "Водачи на градски транспорт", employment: 12000, ai_score: 4, category: "Оператори", avg_salary_eur: 1125 },
  { name: "ВиК оператори", employment: 8000, ai_score: 3, category: "Оператори", avg_salary_eur: 1023 },
  { name: "Телекомуникационни техници", employment: 8000, ai_score: 5, category: "Техници", avg_salary_eur: 1329 },
  { name: "Пощальони", employment: 6000, ai_score: 4, category: "Нискоквалифицирани", avg_salary_eur: 716 },
];
